services:
  - type: web
    name: roblox-shirt-license-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python APP.py
    envVars:
      - key: RUN_MODE
        value: api
      - key: PORT
        value: 10000
      - key: GITHUB_TOKEN
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: GITHUB_REPO
        value: AlfaLuaTest/roblox-shirt-processor-licenses
      - key: GITHUB_BRANCH
        value: main
